name: arnoldi
channels:
  - defaults
  - conda-forge
dependencies:
  - cmake=4.1.1
  - make=4.4.1
  - ffmpeg=7.1.0
  - gcc=15.1.0
  - gfortran=15.1.0
  - python=3.13.7
  - numpy=2.3.2
  - pandas=2.3.2
  - matplotlib=3.10.6